### ISSUE TITLE
What should be the goal for token.py?

### ISSUE THREAD

**Issue by hearot** [pyTeens/nylo#10]
Hello, I was trying to *understand* these lines (they're _function definitions_, see `token.py`), but I can't find what should be the goal. Are they just an help for the _documentation_ or just TODOs?

https://github.com/pyTeens/nylo/blob/5f9e7818586eab1908f75385e385c11ddbce67af/src/nylo/token.py#L13
https://github.com/pyTeens/nylo/blob/5f9e7818586eab1908f75385e385c11ddbce67af/src/nylo/token.py#L16
https://github.com/pyTeens/nylo/blob/5f9e7818586eab1908f75385e385c11ddbce67af/src/nylo/token.py#L23
https://github.com/pyTeens/nylo/blob/5f9e7818586eab1908f75385e385c11ddbce67af/src/nylo/token.py#L30
https://github.com/pyTeens/nylo/blob/5f9e7818586eab1908f75385e385c11ddbce67af/src/nylo/token.py#L38
https://github.com/pyTeens/nylo/blob/5f9e7818586eab1908f75385e385c11ddbce67af/src/nylo/token.py#L46

**Comment by veggero** [comment]
That's documentation.

**Comment by hearot** [comment]
@veggero Okey, thanks ^^
